# Generated by Django 3.2 on 2021-05-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20210513_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fake_id',
            field=models.IntegerField(default=0),
        ),
    ]
