# Generated by Django 3.2 on 2021-05-16 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
